name: smart_calc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  math_expressions: ^2.4.0
  font_awesome_flutter: ^10.7.0
  http: ^1.5.0
  share_plus: ^11.1.0
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  tesseract_ocr: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/